version: "3.9"
services:
  postgres:
    image: postgres:15.6
    environment:
      POSTGRES_DB: "dbtp"
      POSTGRES_USER: "gr401"
      POSTGRES_PASSWORD: "pass123"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"