# Generated by Django 5.0.6 on 2024-06-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(default='Text'),
        ),
    ]
